### ISSUE TITLE
Améliorer l'affichage du code

### ISSUE THREAD

**Issue by alexandre-touret** [alexandre-touret/alexandre-touret.github.io#33]
```
highlighter: rouge
kramdown:
  syntax_highlighter_opts:
    block:
      line_numbers: true
```

https://github.com/mmistakes/minimal-mistakes/discussions/2795
